### PR TITLE
CMakeLists.txt: build on linux

### PR DESCRIPTION
**Pull request by ArnaudValensi**
-changed the 'elif' to 'elseif' because it doesn't work for cmake > 2.6 (specified version).
 -Added missing flags for linux (X11 pthread Xrandr)

### CODE REVIEW

**Comment by bhavyanshu** [comment]
Yup. I can confirm that now it works with the above suggested patch. Tried on Linux 3.5.0-41-generic.

**Comment by farhatnadim** [comment]
confirmed here too as well

**Comment by ghost** [comment]
Merge please.

**Comment by MartinAramini** [comment]
I can confirm it works. Thanks!
@grahamsellers can you merge this into master?

**Pull request closed without merging**
